### ISSUE TITLE
Trouble with stringprep

### ISSUE THREAD

**Issue by berrywira** [buddycloud/buddycloud-http-api#202]
hai, I have tired for this message on log.

Cannot load StringPrep-0.2.3 bindings (using fallback). You may need to `npm install node-stringprep`
Cannot load StringPrep-0.4.0 bindings (using fallback). You may need to `npm install node-stringprep`

I was install node-stringprep on node-modules local or global. but buddycloud-http-api not started.
anybody can help me? Thanks

**Comment by lloydwatkin** [comment]
This is unlikely to be the reason the server will not start. That said do you have libicu-dev installed on your system?

**Comment by berrywira** [comment]
yes, I have libicu-dev installed. any clue again? Thanks

**Comment by berrywira** [comment]
Issue done, Ignore node-stringprep with my solution. Thanks
